# Generated by Django 5.0 on 2023-12-11 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Geeks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='logo_image/', verbose_name='Логотип')),
                ('title1', models.CharField(max_length=255, verbose_name='Название курса')),
                ('title2', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Основные параметры',
                'verbose_name_plural': 'Основные параметры',
            },
        ),
    ]
